server:
  port: 8082

spring:
  application:
    name: video
  datasource:
      driverClassName: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/ds0?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
      username: root
      password: 12345678

mybatis:
  type-aliases-package: com.example.demo.entity
  mapper-locations: classpath:mapper/*Mapper.xml
